# Generated by Django 5.2.4 on 2025-07-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='home_page_show',
            field=models.BooleanField(default=False),
        ),
    ]
