# Generated by Django 5.2.4 on 2025-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthapp', '0002_alter_customuser_phone_number_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
